### ISSUE TITLE
serviceBuilder.js文件是有问题吗？

### ISSUE THREAD

**Issue by sandmanman** [PerseveranceZ/vue-develop-template#2]
您好：
请教。
文件是VSCode打开的。
`serviceBuilder.js` 文件中
`import { LOCAL_AJAX, TEST_PATH } from 'Config'`  该文件中是不是没用到？

提示错误：
`[ts]应为","`
![如图：](https://ws1.sinaimg.cn/large/63ffb79bgy1fsppzjl5itj21j60baade.jpg)

**Comment by PerseveranceZ** [comment]
是的 这个还有之前遗留的 简单逻辑 我删下吧 `serviceBuilder.js` 用不到了
