### ISSUE TITLE
关于构建api文件中遇到的问题

### ISSUE THREAD

**Issue by jadestrong** [PerseveranceZ/vue-develop-template#5]
1.  在`plugins/api.js`文件中，`_apiSingleBuilder`方法中有关于`apiUrl`的`assert`，这个是不是已经没用了！
2. 还是这个地方，有个`mockBaseURL`，在返回的时候作为`baseURL`传给了`axios`，但是这样就会覆盖在`config`中`AXIOS_DEFAULT_CONFIG`设置的全局的`baseURL`。

**Comment by jadestrong** [comment]
但是在不开启mock的情况下，baseURL也会为空，这样会一直覆盖在config配置的baseURL，牵扯到接口前缀中包含接口版本这种情况，例如`/api/v1/xxxx`，需要在全局进行配置的话，这里就不能直接兼容了

**Comment by PerseveranceZ** [comment]
@jadestrong 那就换一种方式，直接拼接 URL 全路径如何？

**Comment by PerseveranceZ** [comment]
[resolve is here](https://github.com/PerseveranceZ/vue-develop-template/commit/8ae3e21854682d347fd669248cc8d39eb9a71895)，thanks for @jadestrong
