### ISSUE TITLE
如何单独控制是否请求mock

### ISSUE THREAD

**Issue by jadestrong** [PerseveranceZ/vue-develop-template#7]
```
// config/index.js

// 当前宿主平台 兼容多平台应该通过一些特定函数来取得
export const HOST_PLATFORM = 'WEB'
// 这个就不多说了
export const NODE_ENV = process.env.NODE_ENV || 'prod'

// 是否强制所有请求访问本地 MOCK，看到这里同学不难猜到，每个请求也可以单独控制是否请求 MOCK
export const AJAX_LOCALLY_ENABLE = false
```
这里提到可以通过上面这个变量来控制是否开启强制访问本地MOCK，以及每个请求也可以单独控制。
* 这个变量好像现在并没有使用吧
* 如何单独控制一个请求呢， 下面还有一个`API_DEFAULT_CONFIG`的配置中有`mock`选项可以控制开启访问mock还是接口，这两个选项是不是有一个就可以， 另外，它也是要控制就都控制了，能实现当个控制吗?

**Comment by PerseveranceZ** [comment]
这样 单独的配置可能就需要在 api 里面单独写了 加一个参数在 plugins/apis 里面判断一下
